tiexin/mywishes/urls.py
from django.conf.urls import url
# from django.contrib.auth import views as auth_views
from . import views

app_name = 'mywishes'

urlpatterns = [
	url(r'^$', views.BrowseAllWishes.as_view(), name='browse'),
	url(r'^create/$', views.CreateAWish.as_view(), name='create'),
	url(r'^create-success/$', views.CreateAWishSuccess.as_view(), name='create-success'),
	url(r'^update/(?P<pk>\d+)/$', views.UpdateAWish.as_view(), name='update'),
	url(r'^update-success/$', views.UpdateAWishSuccess.as_view(), name='update-success'),
	url(r'^delete/(?P<pk>\d+)/$', views.DeleteAWish.as_view(), name='delete'),
	url(r'^delete-success/$', views.DeleteAWishSuccess.as_view(), name='delete-success'),
]

tiexin/tiexin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.core.urlresolvers import reverse
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='accounts/login')),
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	url(r'^mywishes/', include('mywishes.urls', namespace='mywishes')),
    url(r'^toys/', include('toys.urls', namespace='toys')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tiexin/toys/urls.py
from django.conf.urls import url
# from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import TemplateView, RedirectView
from django.core.urlresolvers import reverse_lazy


app_name = 'toys'

urlpatterns = [
	# url(r'^$', views.BrowseAllToys.as_view(), name='browse'),
	url(r'^sell/$', views.UserSellAToy.as_view(), name='sell'),
	url(r'^sell/confirm/$', RedirectView.as_view(url=reverse_lazy('toys:sell')), name="sell-confirm"),
	url(r'^sell/confirm/(?P<toy_source_uuid>.+)/$', views.UserSellConfirm.as_view()),
	url(r'^sell/update/$', RedirectView.as_view(url=reverse_lazy('toys:sell')), name="sell-update"),
	url(r'^sell/update/(?P<toy_source_uuid>.+)/$', views.UserUpdateAToy.as_view()),
	url(r'^sell/success/$', TemplateView.as_view(template_name='toys/sell_success.html'), name='sell-success'),
	url(r'^sell/fail/$', TemplateView.as_view(template_name='toys/sell_fail.html'), name='sell-fail'),

	url(r'^receive-and-approve/(?P<toy_source_id>\d+)$', views.ReceiveAndApprove.as_view(), name='receive-and-approve'),
	# url(r'^add-to-inventory/$', views.AddToInventory.as_view(), name='add-to-inventory'),
	url(r'^add-permission/$', views.AddPermission.as_view()),
	url(r'^remove-permission/$', views.RemovePermission.as_view()),
	url(r'^browse/$', views.BrowseAllToys.as_view(), name='browse'),
	# url(r'^update/(?P<pk>\d+)/$', views.UpdateAToy.as_view(), name='update'),
	# url(r'^update-success/$', views.UpdateAToySuccess.as_view(), name='update-success'),
	# url(r'^delete/(?P<pk>\d+)/$', views.DeleteAToy.as_view(), name='delete'),
	# url(r'^delete-success/$', views.DeleteAToySuccess.as_view(), name='delete-success'),
]

tiexin/mywishes/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Wish(models.Model):
	# django default primary key
	# id = models.AutoField(primary_key=True)
	title = models.CharField(max_length=200)
	proposed_by = models.ForeignKey(User, on_delete=models.CASCADE)
	time = models.DateTimeField()
	location = models.CharField(max_length=200)
	publish_time = models.DateTimeField(auto_now_add=True)
	last_modified = models.DateTimeField(auto_now=True)
	content = models.TextField()
	status = models.CharField(max_length=20)

class WishComment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	wish = models.ForeignKey(Wish, on_delete=models.CASCADE)
	content = models.CharField(max_length=1000)
	publish_time = models.DateTimeField(auto_now_add=True)
	last_modified = models.DateTimeField(auto_now=True)

class WishPopularity(models.Model):
	wish = models.ForeignKey(Wish, on_delete=models.CASCADE)
	n_likes = models.PositiveIntegerField()
	n_dislikes = models.PositiveIntegerField()
	n_views = models.PositiveIntegerField()
	n_forwards = models.PositiveIntegerField()
	n_comments = models.PositiveIntegerField()
	last_modified = models.DateTimeField(auto_now=True)

class WishMedia(models.Model):
	wish = models.ForeignKey(Wish, on_delete=models.CASCADE)
	upload_user = models.ForeignKey(User, on_delete=models.CASCADE)
	time = models.DateTimeField(auto_now_add=True)
	description = models.CharField(max_length=200)
	media_file = models.FileField(upload_to='%Y/%m/%d/')

tiexin/mywishes/forms.py
 #!/usr/bin/python
 # -*- coding: utf-8 -*-

from django import forms
from models import Wish

class WishForm(forms.ModelForm):
	class Meta:
		model = Wish
		fields = ('title', 'time', 'location', 'content')
		labels = {
			'title': '题目',
			'time': '活动时间',
			'location': '活动地点',
			'content': '内容',
		}
		error_message = {
			'title':{
				'max_length': "题目过长"
			}
		}

tiexin/mywishes/views.py
 #!/usr/bin/python
 # -*- coding: utf-8 -*-

from django.shortcuts import render
from django.views.generic import TemplateView, RedirectView, CreateView, DeleteView, UpdateView, ListView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from .forms import WishForm
from .models import Wish
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
import re
from django.db.models import Q


# Create your views here.
class BrowseAllWishes(ListView):
	template_name = 'mywishes/all-wishes.html'
	context_object_name = 'wishes'
	paginate_by = 4

	def get_queryset(self):
		query_string = self.request.GET.get('query', '')
		if query_string == '':
			queryset = Wish.objects.all().order_by('-publish_time')
		else:
			query = None
			terms = normalize_query(query_string)
			search_fields = ['title', 'proposed_by', 'location', 'content', 'status']
			for term in terms:
				or_query = None # Query to search for a given term in each filed
				for field_name in search_fields:
					if field_name == 'proposed_by':
						q = Q(**{'proposed_by__weixinprofile__nickname__contains': term})
					else:
						q = Q(**{'%s__contains' % field_name: term})
					if or_query is None:
						or_query = q
					else:
						or_query = or_query | q

				if query is None:
					query = or_query
				else:
					query = query & or_query
			queryset = Wish.objects.filter(query).order_by('-publish_time')

		return queryset

	def get_context_data(self, **kwargs):
		context = super(BrowseAllWishes, self).get_context_data(**kwargs)
		context['query_string'] = self.request.GET.get('query', '')
		return context

class CreateAWish(LoginRequiredMixin, CreateView):
	# login required mixin
	login_url = reverse_lazy('accounts:login')
	# default: redirect_field_name = 'next'

	# create view
	form_class = WishForm
	template_name = 'mywishes/create_a_wish.html'
	success_url = reverse_lazy('mywishes:browse')


	def get(self, request, *args, **kwargs):
		form = WishForm(initial={
			'title': '贴心网',
			'time':'2016-01-01 6:30:30',
			'location': '嘉兴',
			'content': 'We are awesome!'})
		return self.render_to_response(self.get_context_data(form=form))
		# return render(request, self.template_name, {'form': form})


	def post(self, request, *args, **kwargs):
		form = self.get_form()#WishForm(request.POST)
		if form.is_valid():
			print 'it is valid'
			new_wish = form.save(commit=False)
			print request.user
			new_wish.proposed_by = request.user
			new_wish.status = 'Published'
			new_wish.save()
			return HttpResponseRedirect(self.success_url)
		else:
			print 'it is not valid'
			# return HttpResponseRedirect(self.success_url)
			return self.form_invalid(form)

	def get_context_data(self, **kwargs):
		self.object = None
		context = super(CreateAWish, self).get_context_data(**kwargs)
		return context



class CreateAWishSuccess(TemplateView):
	template_name = 'mywishes/create_success.html'

class UpdateAWish(LoginRequiredMixin, UpdateView):
	# login required mixin
	login_url = reverse_lazy('accounts:login')

	# Update view
	form_class = WishForm
	model = Wish
	template_name = 'mywishes/update_a_wish.html'
	success_url = reverse_lazy('mywishes:browse')

class UpdateAWishSuccess(TemplateView):
	template_name = 'mywishes/update_success.html'

class DeleteAWish(LoginRequiredMixin, DeleteView):
	login_url = reverse_lazy('accounts:login')

	model = Wish
	template_name = 'mywishes/delete_a_wish.html'
	success_url = reverse_lazy('mywishes:browse')

	content_object_name = 'wish'


class DeleteAWishSuccess(TemplateView):
	template_name = 'mywishes/delete_success.html'


def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string in invidual keywords, getting rid of unecessary spaces
        and grouping quoted words together.
        Example:
        
        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']
    
    '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)] 

tiexin/mywishes/templates/mywishes/all-wishes.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<p> You are now logged in as: {{user.weixinprofile.nickname}} </p>
	<form action=".">
		<input type="text" name="query" placeholder="{{query_string}}">
		<input type="submit" value="搜一搜">
	</form>>

	<p><a href=".">显示所有</a></p>
	<p><a href= {%url 'mywishes:create'%}> 新建 </a></p>

	{% for wish in wishes%}
	<p> <img src="{{MEDIA_URL}}{{wish.proposed_by.weixinprofile.headimgurl}}" height="20" width="20" alt="{{MEDIA_URL}}{{wish.proposed_by.weixinprofile.headimgurl}}"/>, {{wish.proposed_by.weixinprofile.nickname}}, {{wish.publish_time}}, {{wish.title}}, {{wish.time}}, {{wish.location}}, {{wish.content}} <a href={% url 'mywishes:update' wish.id %}> 更新 </a> <a href={% url 'mywishes:delete' wish.id %}>   删除 </a> </p>
	{% endfor %}

	<div class="pagination">
		<ul>
			{% if page_obj.has_previous %}
				<li><a href="?page={{page_obj.previous_page_number}}"> Previous </a></li>
			{% endif %}

			{% for pg in page_obj.paginator.page_range %}
				{% if pg == page_obj.number %}
					<li class="active"> <a href="?page={{pg}}"> {{pg}} </a></li>
				{% else %}
				<li> <a href="?page={{pg}}"> {{pg}} </a></li>			
				{% endif %}
			{% endfor %}

			{% if page_obj.has_next%}
			 	<li><a href="?page={{page_obj.next_page_number}}"> Next </a></li>
			{% endif %}
		</ul>

	</div>

{% endblock %}

tiexin/mywishes/templates/mywishes/create_a_wish.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<p> You are now logged in as: {{user}} </p>
	<form method="post">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Submit"/>
	</form>

{% endblock %}

tiexin/mywishes/templates/mywishes/create_success.html
{% extends "base.html" %}
{% load static %}

{% block content %}
You've successfully submit the form!
{% endblock %}

tiexin/mywishes/templates/mywishes/delete_a_wish.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<p> You are now logged in as: {{user}} </p>
	<p>Are you sure you want to delete post {{wish.id}}?</p>
	<p>Title: {{wish.title}}

	<form method="post" action=".">
		{% csrf_token %}
		<input type="submit" value="Delete">
	</form>

{% endblock %}

tiexin/mywishes/templates/mywishes/delete_success.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<p> You are now logged in as: {{user}} </p>
	You've successfully deleted the post
{% endblock %}

tiexin/mywishes/templates/mywishes/update_a_wish.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<p> You are now logged in as:  {{user}}</p>
	<form method="post">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Update"/>
	</form>

{% endblock %}

tiexin/mywishes/templates/mywishes/update_success.html
{% extends "base.html" %}
{% load static %}

{% block content %}
You've successfully updated the wish!
{% endblock %}