tiexin/tiexin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.core.urlresolvers import reverse
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='accounts/login')),
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	url(r'^mywishes/', include('mywishes.urls', namespace='mywishes')),
    url(r'^toys/', include('toys.urls', namespace='toys')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tiexin/toys/urls.py
from django.conf.urls import url
# from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import TemplateView, RedirectView
from django.core.urlresolvers import reverse_lazy


app_name = 'toys'

urlpatterns = [
	# url(r'^$', views.BrowseAllToys.as_view(), name='browse'),
	url(r'^sell/$', views.UserSellAToy.as_view(), name='sell'),
	url(r'^sell/confirm/$', RedirectView.as_view(url=reverse_lazy('toys:sell')), name="sell-confirm"),
	url(r'^sell/confirm/(?P<toy_source_uuid>.+)/$', views.UserSellConfirm.as_view()),
	url(r'^sell/update/$', RedirectView.as_view(url=reverse_lazy('toys:sell')), name="sell-update"),
	url(r'^sell/update/(?P<toy_source_uuid>.+)/$', views.UserUpdateAToy.as_view()),
	url(r'^sell/success/$', TemplateView.as_view(template_name='toys/sell_success.html'), name='sell-success'),
	url(r'^sell/fail/$', TemplateView.as_view(template_name='toys/sell_fail.html'), name='sell-fail'),

	url(r'^receive-and-approve/(?P<toy_source_id>\d+)$', views.ReceiveAndApprove.as_view(), name='receive-and-approve'),
	# url(r'^add-to-inventory/$', views.AddToInventory.as_view(), name='add-to-inventory'),
	url(r'^add-permission/$', views.AddPermission.as_view()),
	url(r'^remove-permission/$', views.RemovePermission.as_view()),
	url(r'^browse/$', views.BrowseAllToys.as_view(), name='browse'),
	# url(r'^update/(?P<pk>\d+)/$', views.UpdateAToy.as_view(), name='update'),
	# url(r'^update-success/$', views.UpdateAToySuccess.as_view(), name='update-success'),
	# url(r'^delete/(?P<pk>\d+)/$', views.DeleteAToy.as_view(), name='delete'),
	# url(r'^delete-success/$', views.DeleteAToySuccess.as_view(), name='delete-success'),
]

tiexin/toys/models.py
 #!/usr/bin/python
 # -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import uuid;

# Create your models here.

def get_fullsize_image_path(instance, filename):
	if isinstance(instance, ToySource):
		folder_name = 'source'
	elif isinstance(instance, ToyInventory):
		folder_name = 'inventory'
	else:
		folder_name = 'unknown'
	return '/'.join(['toys', folder_name, instance.uuid, 'fullsize', filename])

def get_thumbnail_image_path(instance, filename):
	if isinstance(instance, ToySource):
		folder_name = 'source'
	elif isinstance(instance, ToyInventory):
		folder_name = 'inventory'	
	else:
		folder_name = 'unknown'
	return '/'.join(['toys', folder_name, instance.uuid, 'thumbnail', filename])

def get_uuid():
	return str(uuid.uuid4())

class Toy(models.Model):
	# django default primary key
	# id = models.AutoField(primary_key=True)
	# uuid is used for user upload picture folder name
	uuid = models.CharField(max_length=36, default=get_uuid, editable=False)
	title = models.CharField(max_length=200)
	status = models.CharField(max_length=100)
	description = models.TextField()
	brand = models.CharField(max_length=100)


	sold_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sold_by')
	sold_by_propose_price = models.DecimalField(max_digits=6, decimal_places=2,default=0)
	sold_by_propose_time = models.DateTimeField()
	sold_by_accept_price = models.DecimalField(max_digits=6, decimal_places=2,default=0)
	sold_by_accept_time = models.DateTimeField(null=True)

	sell_price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
	sold_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sold_to', null=True)
	sold_to_time = models.DateTimeField(null=True)

	publish_time = models.DateTimeField(null=True)
	last_modified = models.DateTimeField(auto_now=True)

	num_images = models.PositiveSmallIntegerField(default=0)
	image1 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
	image2 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
 	image3 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
 	image4 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
 	image5 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
	image1_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
	image2_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
 	image3_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
 	image4_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
 	# image5_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)



class ToySource(models.Model):

	class Meta:
		permissions = (
			('approve_toy', "Can approve a user's toy and finalize the quote"),
		)


	# django default primary key
	# id = models.AutoField(primary_key=True)

	# User entry
	title = models.CharField(max_length=200)
	brand = models.CharField(max_length=100)
	original_cost = models.PositiveIntegerField(null=True, blank=True)
	original_vendor = models.CharField(max_length=100)
	has_original_receipt = models.CharField(max_length=10)
	purchase_time = models.CharField(max_length=50)
	exterior = models.CharField(max_length=100)
	functionality = models.CharField(max_length=100)
	description = models.TextField(null=True, blank=True)
	image1 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
	image2 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
 	image3 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
 	image4 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
 	image5 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
	image1_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
	image2_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
 	image3_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
 	image4_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
 	image5_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)

 	# More Toy/User info
	# uuid is used for user upload picture folder name
	uuid = models.CharField(max_length=36, default=get_uuid, editable=False)
	seller = models.ForeignKey(User, on_delete=models.PROTECT)
	num_images = models.PositiveSmallIntegerField(default=0)
	submit_date = models.DateTimeField()
	instant_quote_point = models.PositiveIntegerField(default=0)
	instant_quote_discount = models.PositiveIntegerField(default=0)
	is_instant_quote_accepted = models.NullBooleanField()
	status = models.CharField(max_length=100)
	status_last_modified = models.DateTimeField(null=True)

	# Admin entry
	receive_date = models.DateTimeField(null=True)
	final_quote = models.PositiveIntegerField(default=0)
	comment = models.TextField(null=True, blank=True)
	is_final_quote_accepted = models.BooleanField(default=False)
	is_complete = models.BooleanField(default=False)

	def __unicode__(self):
		return self.title + '-' + self.brand + '-' + self.original_vendor

class ToyInventory(models.Model):
	toy_source = models.ForeignKey(ToySource, on_delete=models.PROTECT)
	title = models.CharField(max_length=200)
	brand = models.CharField(max_length=100)
	original_vendor = models.CharField(max_length=100, null=True)
	purchase_time = models.CharField(max_length=50)
	exterior = models.CharField(max_length=100)
	functionality = models.CharField(max_length=100)
	description = models.TextField()

	buy_in_price_point = models.PositiveIntegerField(default=0)
	sell_price_point = models.PositiveIntegerField()

	add_time = models.DateTimeField(auto_now_add=True)
	last_modified = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=100)
	status_last_modified = models.DateTimeField(null=True)

	num_images = models.PositiveSmallIntegerField(default=0)
	image1 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
	image2 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
 	image3 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
 	image4 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
 	image5 = models.ImageField(upload_to=get_fullsize_image_path, max_length=200, null=True)
	image1_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
	image2_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
 	image3_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
 	image4_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)
 	image5_thumbnail = models.ImageField(upload_to=get_thumbnail_image_path, max_length=200, null=True)

tiexin/toys/forms.py
 #!/usr/bin/python
 # -*- coding: utf-8 -*-

from django import forms
from models import Toy, ToySource

class SellAToyForm(forms.ModelForm):
	class Meta:
		model = Toy
		fields = ['title', 'description', 'brand', 'sold_by_propose_price']
		# fields = ['title', 'description', 'brand', 'sold_by_propose_price']

		labels = {
			'title': "产品名称",
			'description': "描述",
			'brand': "品牌",
			'sold_by_propose_price': "提议价格",
		 }

		widgets = {
		 	'title': forms.TextInput(attrs={'class': 'form-control'}),
		 	'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '6'}),
			'brand': forms.TextInput(attrs={'class': 'form-control'}),
			'sold_by_propose_price': forms.NumberInput(attrs={'class': 'form-control', 'step': '1'}),
		 }


class UpdateAToyForm(forms.ModelForm):
	class Meta:
		model = Toy
		fields = ['title', 'status', 'description', 'brand', 'sold_by', 'sold_by_propose_time',  'sold_by_propose_price', 'sold_by_accept_time', 'sold_by_accept_price', 'sell_price', 'publish_time']

EMPTY_CHOICE = ('', '------')

def make_choices(choice_list):
	choices = (EMPTY_CHOICE, )
	for choice in choice_list:
		choices += ((choice, choice),)
	return choices

HAS_ORIGINAL_RECEIPT_CHOICES = make_choices(['有', '没有'])
PURCHASE_TIME_CHOICES = make_choices(['一个月以内', '三个月以内', '六个月以内', '一年以内', '两年以内', '三年以内', '三年以上'])
EXTERIOR_CHOICES  = make_choices(['全新未拆封','外观完好','外观有轻微损伤或褪色','外观有明显损伤'])
FUNCTIONALITY_CHOICES = make_choices(['功能正常', '缺失非功能性配件', '无法正常使用'])

class UserSellAToyForm(forms.ModelForm):
	class Meta:
		model = ToySource
		fields = ['title', 'brand', 'original_cost', 'original_vendor','has_original_receipt', 'purchase_time', 'exterior', 'functionality','description']

		labels = {
			'title': '产品名称',
			'brand': '品牌',
			'original_cost': '购买价格',
			'original_vendor': '购买途径',
			'has_original_receipt': '购买票据',
			'purchase_time': '购买时间',
			'exterior': '外观',
			'functionality': '功能',
			'description': '补充描述',
		 }

		widgets = {
			'title': forms.TextInput(attrs={'class': 'form-control'}),
			'brand': forms.TextInput(attrs={'class': 'form-control'}),
			'original_cost': forms.NumberInput(attrs={'class': 'form-control','step':'1'}),
			'original_vendor': forms.TextInput(attrs={'class': 'form-control'}),
			'has_original_receipt': forms.Select(choices=HAS_ORIGINAL_RECEIPT_CHOICES, attrs={'class': 'form-control'}),
			'purchase_time': forms.Select(choices=PURCHASE_TIME_CHOICES, attrs={'class': 'form-control'}),
			'exterior': forms.Select(choices=EXTERIOR_CHOICES, attrs={'class': 'form-control'}),
			'functionality': forms.Select(choices=FUNCTIONALITY_CHOICES, attrs={'class': 'form-control'}),
			'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
		 }

class ReceiveAndApproveForm(forms.ModelForm):
	class Meta:
		model = ToySource
		exclude = []

tiexin/toys/templates/toys/add_permission.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class="container div-margin-top full-width">
		<div class="row">
			<div class="col-sm-6 col-sm-offset-3">
				You've successfully added 'approve-toy' permission to {{user}}!
				add new ones.
			</div>
		</div>
	</div>
{% endblock %}

tiexin/toys/templates/toys/browse_all_toys.html
{% extends "base.html" %}
{% load staticfiles %}

{% block custom_css %}
	<link href="{%static 'toys/css/browse_all_toys.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
	<div class="container div-margin-top full-width">
		<div class="display-toys row">
			{% for toy in toys%}
			<div class="toy-container col-sm-3 col-lg-2">
				{% if toy.image1 %}
				<img src="{{toy.image1_thumbnail.url}}" height="150"/>
				{% else %}
				<img src="{{MEDIA_URL}}toys/question/question_thumbnail.jpg" height="150"/>
				{% endif %}
				<div class="toy-price"> {{toy.sold_by_propose_price}}元</div>
				<div class="toy-title">{{toy.title}}</div>
				<div class="toy-brand">{{toy.brand}}</div>
			</div>
			{% endfor %}
		</div>

		<div class="pagination">
			<ul>
				{% if page_obj.has_previous %}
					<li class="active-pg-block"><a href="?page={{page_obj.previous_page_number}}"> 上一页 </a></li>
				{% else %}
					<li class="inactive-pg-block"> 上一页 </li>
				{% endif %}
	
				{% for pg in page_obj.paginator.page_range %}
					{% if pg == page_obj.number %}
					<li class="inactive-pg-block">{{pg}}</li>
					{% else %}
					<li class="active-pg-block"><a href="?page={{pg}}">{{pg}}</a></li>
					{% endif %}
				{% endfor %}


				{% if page_obj.has_next%}
				 	<li class="active-pg-block"><a href="?page={{page_obj.next_page_number}}"> 下一页 </a></li>
				 {% else %}
				 	<li class="inactive-pg-block"> 下一页 </li>
				{% endif %}
			</ul>
		</div>
	</div>


{% endblock %}

tiexin/toys/templates/toys/receive_and_approve.html
{% extends "base.html" %}
{% load staticfiles %}

{% block custom_css %}
	<link href="{%static 'toys/css/user_sell_a_toy.css' %}" rel="stylesheet"/>
	<link href="{%static 'toys/css/user_update_a_toy.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
	<div class="container div-margin-top full-width">
		<div class="row">
			<div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
				<form method="post" enctype="multipart/form-data" class="horizontal-form">
					{% csrf_token %}

					{% for field in form %}
					{% if field.errors %}
					<div class="form-group row has-error has-feedback">
					{% else %}
					<div class="form-group row">
					{% endif %}
						<label for="{{field.id_for_label}}" class="col-xs-4 control-label no-padding"> <span>{{field.label}} {% if field.field.required%} * {%endif%}</span></label>

						<div class="col-xs-8">
							{% if field == form.original_cost %}
								<div class="input-group">
									{{field}}
									<div class="input-group-addon">元</div>
								</div>
							{% else %}
								{{field}}
							{% endif %}

							{% if field.errors %}
						    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
	    					{% endif %}
						</div>
					</div>
					{% endfor %}

					<div class="form-group row">
						<label class="col-xs-4 control-label no-padding" id="uploaded-image-label">已上传图片</label>
						<div class="col-xs-8 row uploaded-images">
							{% for image_url in image_urls%}
							<img class="img-responsive uploaded-thumbnail" src="{{image_url}}"/>
							{% endfor %}
						</div>
					</div>

					<div class="form-group row">
						<label class="col-xs-4 control-label no-padding" id="image-label">图片</label>
						<div class="col-xs-8" id="input-files">
							<div class="input-group row">
								<input type="file" name="image1" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">&times</span>
							</div>

							<div class="input-group row">
								<input type="file" name="image2" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">&times</span>
							</div>

							<div class="input-group row">
								<input type="file" name="image3" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">&times</span>
							</div>

							<div class="input-group row">
								<input type="file" name="image4" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">&times</span>
							</div>

							<div class="input-group row">
								<input type="file" name="image5" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">&times</span>
							</div>
						</div>
					</div>

					<div class="form-group row">
						<div class="col-xs-4"></div>
						<div class="col-xs-8">
							<input type="submit" class="btn btn-success btn-submit" value="获取估值"/>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

{% block custom_js %}
	<script src="{% static 'toys/js/bootstrap.file-input.js'%}"></script>

	<script>
		// initialize the file input buttons
		$(document).ready(function(){
			$(".file-input").bootstrapFileInput();
			$("#input-files").children().addClass("hide");
			var image_start_num = $(".uploaded-images").find(".uploaded-thumbnail").length+1
			if(image_start_num==6){
				$("#image-label").text("");
			}else{
				$("#image-label").text("图片");
			}
			if(image_start_num==1){
				$("#uploaded-image-label").text("");
			}else{
				$("#uploaded-image-label").text("已上传图片");
			}

			$("#input-files .input-group:nth-child("+image_start_num+")").removeClass("hide");
		});

		// after choosing a file, add the cancel button and another file select button
		$("#input-files").children().on("change", function(){
			$(this).children(".btn-cancel").removeClass("hide");
			$(this).next().removeClass("hide");
		});

		// remove files with the cancel button
		$(".btn-cancel").on("click", function(){
			$(this).addClass("hide");
			$(this).prev().children("span").text("添加图片");
			var input_elem = $(this).prev().children("input");
			input_elem.wrap('<form>').parent('form').trigger('reset');
		    input_elem.unwrap();
		})
	</script>


	<script type="text/javascript"> 
		function stopRKey(evt) { 
		  var evt = (evt) ? evt : ((event) ? event : null); 
		  var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null); 
		  if ((evt.keyCode == 13) && (node.type=="text"))  {return false;} 
		} 
		document.onkeypress = stopRKey; 
	</script>
{% endblock %}

tiexin/toys/templates/toys/remove_permission.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class="container div-margin-top full-width">
		<div class="row">
			<div class="col-sm-6 col-sm-offset-3">
				You've successfully removed 'approve-toy' permission to {{user}}!
			</div>
		</div>
	</div>
{% endblock %}

tiexin/toys/templates/toys/sell_a_toy.html
{% extends "base.html" %}
{% load staticfiles %}

{% block custom_css %}
	<link href="{%static 'toys/css/sell_a_toy.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
	<div class="container div-margin-top full-width">
		<div class="row">
			<div class="col-sm-6 col-sm-offset-3">
				<form method="post" enctype="multipart/form-data" class="horizontal-form">
					{% csrf_token %}
					{% if form.title.errors %}
					<div class="form-group row has-error has-feedback">
					{% else %}
					<div class="form-group row">
					{% endif %}
						<label for="id_title" class="col-sm-3 control-label no-padding"> {{form.title.label}}</label>
						<div class="col-sm-6 ">
							{{form.title}}
							{% if form.title.errors %}
						    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
						    <span id="id_title_status" class="sr-only">(error)</span>
	    					{% endif %}
						</div>
					</div>

					{% if form.brand.errors %}
					<div class="form-group row has-error has-feedback">
					{% else %}
					<div class="form-group row">
					{%endif%}
						<label for="id_brand" class="col-sm-3 control-label"> {{form.brand.label}}</label>
						<div class="col-sm-6">
							{{form.brand}}
							{% if form.brand.errors %}
						    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
						    <span id="id_brand_status" class="sr-only">(error)</span>
	    					{% endif %}

						</div>
					</div>

					{% if form.description.errors %}
					<div class="form-group row has-error has-feedback">
					{% else %}
					<div class="form-group row">
					{%endif%}
						<label for="id_description" class="col-sm-3 control-label"> {{form.description.label}}</label>
						<div class="col-sm-6">
							{{form.description}}
							{% if form.description.errors %}
						    <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
						    <span id="id_description_status" class="sr-only">(error)</span>
	    					{% endif %}
						</div>
					</div>

					{% if form.sold_by_propose_price.errors %}
					<div class="form-group row has-error has-feedback">
					{% else %}
					<div class="form-group row">
					{%endif%}
						<label for="id_sold_by_propose_price" class="col-sm-3 control-label"> {{form.sold_by_propose_price.label}}</label>
						<div class="col-sm-6">
							<div class="input-group">
								{{form.sold_by_propose_price}}
								<div class="input-group-addon">元</div>
							</div>
							{% if form.sold_by_propose_price.errors %}
						    <span id="sold_by_propose_price_error" class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
						    <span id="id_sold_by_propose_price_status" class="sr-only">(error)</span>
	    					{% endif %}
						</div>
					</div>

					<div class="form-group row">
						<label class="col-sm-3 control-label">上传图片</label>
						<div class="col-sm-6" id="input-files">
							<div class="input-group row">
								<input type="file" id="image1" name="image1" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">X</span>
							</div>

							<div class="input-group row">
								<input type="file" name="image2" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">X</span>
							</div>

							<div class="input-group row">
								<input type="file" name="image3" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">X</span>
							</div>

							<div class="input-group row">
								<input type="file" name="image4" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">X</span>
							</div>

							<div class="input-group row">
								<input type="file" name="image5" class="btn btn-primary file-input" title="添加图片" data-filename-placement="inside">
								<span class="cancel-file btn btn-cancel hide">X</span>
							</div>
						</div>
					</div>

					<div>
						<div class="form-group row">
							<div class="col-sm-3"></div>
							<div class="col-sm-6">
								<input type="submit" name="cancel" class="btn btn-primary btn-submit" value="取消"/>
								<input type="submit" class="btn btn-primary btn-submit" value="提交"/>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

{% block custom_js %}
	<script src="{% static 'toys/js/bootstrap.file-input.js'%}"></script>
	<script>
		$(document).ready(function(){
			$(".file-input").bootstrapFileInput();
			$("#input-files").children().addClass("hide");
			$("#input-files").children().first().removeClass("hide");
		});

		$("#input-files").children().on("change", function(){
			$(this).children(".btn-cancel").removeClass("hide");
			$(this).next().removeClass("hide");
		});

		$(".btn-cancel").on("click", function(){
			$(this).addClass("hide");
			$(this).prev().children("span").text("添加图片");
			var input_elem = $(this).prev().children("input");
			input_elem.wrap('<form>').parent('form').trigger('reset');
		    input_elem.unwrap();
		})
	</script>
	<script type="text/javascript"> 
	function stopRKey(evt) { 
	  var evt = (evt) ? evt : ((event) ? event : null); 
	  var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null); 
	  if ((evt.keyCode == 13) && (node.type=="text"))  {return false;} 
	} 
	document.onkeypress = stopRKey; 
	</script>
{% endblock %}

tiexin/toys/templates/toys/sell_fail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class="container div-margin-top full-width">
		<div class="row">
			<div class="col-sm-6 col-sm-offset-3">
				FAIL!
			</div>
		</div>
	</div>
{% endblock %}

tiexin/toys/templates/toys/sell_success.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class="container div-margin-top full-width">
		<div class="row">
			<div class="col-sm-6 col-sm-offset-3">
				You've successfully submitted one toy!
			</div>
		</div>
	</div>
{% endblock %}